<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Transaksi;

class TransaksiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
    
        // Data Dummy Riwayat Transaksi Penyewa

        $dataPenyewa = [
            [
                'kode_transaksi' => 'TRX-20260901-0042',
                'role' => 'penyewa',
                'nama_toko' => 'Vynelle Market',
                'foto_toko' => 'store-vynelle.png',
                'nama_penyewa' => 'Nugra Hashattan',
                'foto_penyewa' => 'profile-1.png',
                'nama_produk' => 'Tank M103 Counter Soviet Tahun 1960 Sekali Tembak Rata',
                'foto_produk' => 'tank-m103.png',
                'varian' => null,
                'jumlah' => '1 Buah',
                'tanggal_mulai' => '2026-09-05',
                'tanggal_selesai' => '2026-09-08',
                'durasi' => 3,
                'total_harga' => 5000000,
                'status' => 'diproses',
            ],
            [
                'kode_transaksi' => 'TRX-20260828-0187',
                'role' => 'penyewa',
                'nama_toko' => 'Vynelle Market',
                'foto_toko' => 'store-vynelle.png',
                'nama_penyewa' => 'Nugra Hashattan',
                'foto_penyewa' => 'profile-1.png',
                'nama_produk' => 'Iphone 17 Pro Max',
                'foto_produk' => 'iphone-17.png',
                'varian' => '100 TB',
                'jumlah' => '1 Buah',
                'tanggal_mulai' => '2026-08-28',
                'tanggal_selesai' => '2026-08-30',
                'durasi' => 2,
                'total_harga' => 400000,
                'status' => 'selesai',
            ],
            [
                'kode_transaksi' => 'TRX-20260901-0043',
                'role' => 'penyewa',
                'nama_toko' => 'Vynelle Market',
                'foto_toko' => 'store-vynelle.png',
                'nama_penyewa' => 'Nugra Hashattan',
                'foto_penyewa' => 'profile-1.png',
                'nama_produk' => 'Kompor Listrik Portable',
                'foto_produk' => 'kompor-listrik.png',
                'varian' => null,
                'jumlah' => '1 Buah',
                'tanggal_mulai' => '2026-09-08',
                'tanggal_selesai' => '2026-09-12',
                'durasi' => 4,
                'total_harga' => 65000,
                'status' => 'disewa',
            ],
            [
                'kode_transaksi' => 'TRX-20260901-0044',
                'role' => 'penyewa',
                'nama_toko' => 'Vynelle Market',
                'foto_toko' => 'store-vynelle.png',
                'nama_penyewa' => 'Nugra Hashattan',
                'foto_penyewa' => 'profile-1.png',
                'nama_produk' => 'Macbook Pro',
                'foto_produk' => 'macbook-pro.png',
                'varian' => null,
                'jumlah' => '1 Buah',
                'tanggal_mulai' => '2026-05-10',
                'tanggal_selesai' => '2026-05-13',
                'durasi' => 3,
                'total_harga' => 500000,
                'status' => 'pengembalian',
            ],
            [
                'kode_transaksi' => 'TRX-20260828-0188',
                'role' => 'penyewa',
                'nama_toko' => 'Vynelle Market',
                'foto_toko' => 'store-vynelle.png',
                'nama_penyewa' => 'Nugra Hashattan',
                'foto_penyewa' => 'profile-1.png',
                'nama_produk' => 'Kebaya One Set',
                'foto_produk' => 'kebaya.png',
                'varian' => 'Navy',
                'jumlah' => '1 Buah',
                'tanggal_mulai' => '2026-05-08',
                'tanggal_selesai' => '2026-05-10',
                'durasi' => 3,
                'total_harga' => 200000,
                'status' => 'dibatalkan',
            ],
            [
                'kode_transaksi' => 'TRX-20260901-0045',
                'role' => 'penyewa',
                'nama_toko' => 'Zenvy Market',
                'foto_toko' => 'store-zenvy.png',
                'nama_penyewa' => 'Nugra Hashattan',
                'foto_penyewa' => 'profile-1.png',
                'nama_produk' => 'Drum',
                'foto_produk' => 'drum.png',
                'varian' => null,
                'jumlah' => '1 Buah',
                'tanggal_mulai' => '2026-05-07',
                'tanggal_selesai' => '2026-05-10',
                'durasi' => 3,
                'total_harga' => 150000,
                'status' => 'belum_dikembalikan',
            ],
            [
                'kode_transaksi' => 'TRX-20260901-0046',
                'role' => 'penyewa',
                'nama_toko' => 'IBOX',
                'foto_toko' => 'store-ibox.png',
                'nama_penyewa' => 'Nugra Hashattan',
                'foto_penyewa' => 'profile-1.png',
                'nama_produk' => 'I Watch',
                'foto_produk' => 'iwatch.png',
                'varian' => 'Gen 4',
                'jumlah' => '1 Buah',
                'tanggal_mulai' => '2026-05-08',
                'tanggal_selesai' => '2026-05-12',
                'durasi' => 4,
                'total_harga' => 200000,
                'status' => 'kerusakan',
            ],
        ];


        
        // Data Dummy Riwayat Transaksi Pemilik

        $dataPemilik = [
            [
                'kode_transaksi' => 'TRX-20260828-0187',
                'role' => 'pemilik',
                'nama_toko' => 'Vynelle Market',
                'foto_toko' => 'store-vynelle.png',
                'nama_penyewa' => 'Nugra Hashattan',
                'foto_penyewa' => 'profile-1.png',
                'nama_produk' => 'Iphone 17 Pro Max',
                'foto_produk' => 'iphone-17.png',
                'varian' => '100 TB',
                'jumlah' => '1 Buah',
                'tanggal_mulai' => '2026-08-28',
                'tanggal_selesai' => '2026-08-30',
                'durasi' => 2,
                'total_harga' => 400000,
                'status' => 'selesai',
            ],
            [
                'kode_transaksi' => 'TRX-20260828-0188',
                'role' => 'pemilik',
                'nama_toko' => 'Vynelle Market',
                'foto_toko' => 'store-vynelle.png',
                'nama_penyewa' => 'Tariq Halilintar',
                'foto_penyewa' => 'profile-2.png',
                'nama_produk' => 'Sepeda Gunung',
                'foto_produk' => 'sepeda-gunung.png',
                'varian' => null,
                'jumlah' => '1 Buah',
                'tanggal_mulai' => '2026-08-28',
                'tanggal_selesai' => '2026-08-30',
                'durasi' => 2,
                'total_harga' => 70000,
                'status' => 'pesanan_masuk',
            ],
            [
                'kode_transaksi' => 'TRX-20260828-0189',
                'role' => 'pemilik',
                'nama_toko' => 'Vynelle Market',
                'foto_toko' => 'store-vynelle.png',
                'nama_penyewa' => 'Nugra Hashattan',
                'foto_penyewa' => 'profile-1.png',
                'nama_produk' => 'Panci Listrik',
                'foto_produk' => 'panci-listrik.png',
                'varian' => null,
                'jumlah' => '1 Buah',
                'tanggal_mulai' => '2026-08-28',
                'tanggal_selesai' => '2026-08-30',
                'durasi' => 2,
                'total_harga' => 60000,
                'status' => 'disewa',
            ],
            [
                'kode_transaksi' => 'TRX-20260901-0047',
                'role' => 'pemilik',
                'nama_toko' => 'Vynelle Market',
                'foto_toko' => 'store-vynelle.png',
                'nama_penyewa' => 'Nugra Hashattan',
                'foto_penyewa' => 'profile-1.png',
                'nama_produk' => 'Coffee Maker',
                'foto_produk' => 'coffee-maker.png',
                'varian' => null,
                'jumlah' => '1 Buah',
                'tanggal_mulai' => '2026-05-09',
                'tanggal_selesai' => '2026-05-13',
                'durasi' => 4,
                'total_harga' => 100000,
                'status' => 'pengembalian',
            ],
            [
                'kode_transaksi' => 'TRX-20260901-0048',
                'role' => 'pemilik',
                'nama_toko' => 'Vynelle Market',
                'foto_toko' => 'store-vynelle.png',
                'nama_penyewa' => 'Nugra Hashattan',
                'foto_penyewa' => 'profile-1.png',
                'nama_produk' => 'Kamera Instax',
                'foto_produk' => 'kamera-instax.png',
                'varian' => null,
                'jumlah' => '1 Buah',
                'tanggal_mulai' => '2026-05-09',
                'tanggal_selesai' => '2026-05-13',
                'durasi' => 4,
                'total_harga' => 100000,
                'status' => 'dibatalkan',
            ],
            [
                'kode_transaksi' => 'TRX-20260901-0049',
                'role' => 'pemilik',
                'nama_toko' => 'Vynelle Market',
                'foto_toko' => 'store-vynelle.png',
                'nama_penyewa' => 'Nugra Hashattan',
                'foto_penyewa' => 'profile-1.png',
                'nama_produk' => 'Raket Tenis',
                'foto_produk' => 'raket-tenis.png',
                'varian' => null,
                'jumlah' => '1 Buah',
                'tanggal_mulai' => '2026-05-07',
                'tanggal_selesai' => '2026-05-10',
                'durasi' => 3,
                'total_harga' => 75000,
                'status' => 'belum_dikembalikan',
            ],
            [
                'kode_transaksi' => 'TRX-20260901-0050',
                'role' => 'pemilik',
                'nama_toko' => 'Vynelle Market',
                'foto_toko' => 'store-vynelle.png',
                'nama_penyewa' => 'Nugra Hashattan',
                'foto_penyewa' => 'profile-1.png',
                'nama_produk' => 'Iphone 16 Pro Max',
                'foto_produk' => 'iphone-16.png',
                'varian' => 'Gen 4',
                'jumlah' => '1 Buah',
                'tanggal_mulai' => '2026-05-08',
                'tanggal_selesai' => '2026-05-12',
                'durasi' => 4,
                'total_harga' => 200000,
                'status' => 'kerusakan',
            ],
        ];

        foreach (array_merge($dataPenyewa, $dataPemilik) as $data) {
            Transaksi::updateOrCreate(
                [
                    'kode_transaksi' => $data['kode_transaksi'],
                ],
                $data
            );
        }
    }
}